name: Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - uses: chartboost/ruff-action@v1

      - name: Test with pytest
        run: |
          pip install pytest
          pytest
